apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
    - name: run-image
      value: gcr.io/taaron-1/tanzu-java-web-app
  source:
    git:
      url: https://github.com/garreeoke/tanzu-java-web-app-2
      ref:
        branch: main
